name: 'setup-arkade'
description: 'Setup arkade cli'
author: 'openfaas'
inputs:
  version: # change this
    required: false
    description: 'this is the version of the arkade cli'
    default: '0.6.22'
runs:
  using: 'node12'
  main: 'dist/index.js'
